# Generated by Django 3.0.6 on 2023-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_setting',
            fields=[
                ('mail_seq', models.AutoField(primary_key=True, serialize=False)),
                ('mail_sender_host', models.CharField(max_length=30, null='FALSE')),
                ('smtp_port', models.CharField(max_length=12, null='FALSE')),
                ('sender_user', models.CharField(max_length=24, null='FALSE')),
                ('sender_password', models.CharField(max_length=30, null='FALSE')),
            ],
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=32, null='FALSE')),
                ('user_pw', models.CharField(max_length=20, null='FALSE')),
                ('user_name', models.CharField(default='이름을 설정하세요', max_length=20)),
                ('user_email', models.CharField(default='E-mail을 설정하세요', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
