# Generated by Django 4.2.5 on 2023-09-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_user_master_user_actiavte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_master',
            old_name='user_actiavte',
            new_name='user_activate',
        ),
    ]
