# Generated by Django 4.2.5 on 2023-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_user_actiavte_user_master_user_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_log',
            fields=[
                ('mail_seq', models.AutoField(primary_key=True, serialize=False)),
                ('mail_title', models.CharField(max_length=200, null='FALSE')),
                ('mail_to', models.CharField(max_length=200, null='FALSE')),
                ('mail_from', models.CharField(max_length=200, null='FALSE')),
                ('mail_body', models.CharField(max_length=200, null='FALSE')),
                ('mail_bcc', models.CharField(max_length=200, null='FALSE')),
                ('mail_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
